name: Fly Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Vérifie le code depuis la branche
      - name: Checkout code
        uses: actions/checkout@v3

      # Installe Flyctl
      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      # Authentifie Fly.io
      - name: Authenticate with Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: fly auth token $FLY_API_TOKEN

      # Déploie sur Fly.io
      - name: Deploy to Fly.io
        run: fly deploy