name: Fly Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Authenticate with Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: fly auth login --access-token $FLY_API_TOKEN

      - name: Validate Fly.io Authentication
        run: fly auth whoami

      - name: Check Flyctl version
        run: fly version

      - name: Deploy to Fly.io
        run: fly deploy